name: Format check
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 8 * * *' #every day at 8am

jobs:
  formatCheck:
    runs-on: ubuntu-latest
    steps:
    - name: MeshFields Checkout repo
      uses: actions/checkout@v4
      with:
        repository: SCOREC/meshFields
        path: meshFields

    - name: Install clang-format-15
      run: |
        sudo apt-get update -yq
        sudo apt-get install -yq clang-format-15
        
    - name: Format check
      working-directory: meshFields
      shell: bash
      run: |
       clang-format-15 --version
       clang-format-15 --dry-run --Werror src/* test/*
